# Site settings
title: Ignat Zakrevsky
email: iezakrevsky@gmail.com
description: Software Developer blog about what I'm doing and how
baseurl: ""
url: "http://ignat-z.github.io"
github_username:  ignat-z

# Build settings
markdown: kramdown
exclude: [vendor]
gems:
  - jekyll-sitemap
