# Site settings
title: Ignat Zakrevsky
email: iezakrevsky@gmail.com
description: Software Developer blog about what I'm doing and how
baseurl: ""
url: "http://ignat-zakrevsky.github.io"
github_username:  ignat-zakrevsky

# Build settings
markdown: kramdown
exclude: [vendor]
gems:
  - jekyll-sitemap
