title: Ignat Z
email: iezakrevsky@gmail.com
description: Contacts of Ignat Zakrevsky
url: "https://ignat-z.github.io"

exclude: [vendor]
markdown: kramdown
plugins:
  - jekyll-sitemap
sass:
  style: compressed
